// Generated on 2014-03-13 using generator-bespoke v0.8.0

module.exports = function(grunt) {

  var config = {
    clean: {
      public: 'public/**/*'
    },
    jade: {
      src: {
        files: [{
          expand: true,
          cwd: 'src/',
          src: '**/*.jade',
          dest: 'public/',
          ext: '.html'
        }],
        options: {
          pretty: true
        }
      }
    },
    sass: {
      src: {
        files: [{
          expand: true,
          cwd: 'src/styles/',
          src: '**/*.scss',
          dest: 'public/styles/',
          ext: '.css'
        }]
      }
    },
    autoprefixer: {
      src: {
        files: [{
          expand: true,
          cwd: 'public/styles',
          src: ['**/*.css'],
          dest: 'public/styles',
        }]
      }
    },
    concat: {
      js: {
        files: [{
          src: [
            'src/bower_components/bespoke.js/dist/bespoke.min.js',
            'src/bower_components/bespoke-keys/dist/bespoke-keys.min.js',
            'src/bower_components/bespoke-touch/dist/bespoke-touch.min.js',
            'src/bower_components/bespoke-scale/dist/bespoke-scale.min.js',
            'src/bower_components/bespoke-hash/dist/bespoke-hash.min.js',
            'src/bower_components/bespoke-state/dist/bespoke-state.min.js',
            'src/bower_components/bespoke-bullets/dist/bespoke-bullets.min.js',
            'src/bower_components/prism/prism.js',
            'src/bower_components/prism/components/prism-bash.js',
            'src/bower_components/prism/components/prism-css.js',
            'src/bower_components/prism/components/prism-css-extras.js',
            'src/scripts/**/*.js'
          ],
          dest: 'public/scripts/scripts.js'
        }]
      }
    },
    copy: {
      src: {
        files: [{
          expand: true,
          cwd: 'src/',
          src: [
            '**/*',
            '!**/*.js',
            '!<%= jade.src.files[0].src %>',
            '!<%= sass.src.files[0].src %>'
          ],
          dest: 'public/'
        }]
      }
    },
    watch: {
      jade: {
        files: '<%= jade.src.files[0].cwd + jade.src.files[0].src %>',
        tasks: 'jade'
      },
      sass: {
        files: '<%= sass.src.files[0].cwd + sass.src.files[0].src %>',
        tasks: ['compile-sass']
      },
      copy: {
        files: [
          '<%= copy.src.files[0].cwd + copy.src.files[0].src[0] %>',
          '!src/scripts/**/*.js',
          '!<%= jade.src.files[0].cwd + jade.src.files[0].src %>',
          '!<%= sass.src.files[0].cwd + sass.src.files[0].src %>'
        ],
        tasks: 'copy:src'
      },
      public: {
        files: [
          'public/**/*',
          '!public/bower_components/**/*'
        ],
        options: {
          livereload: 35729
        }
      }
    },
    connect: {
      server: {
        options: {
          port: 8000,
          hostname: '*', // Remove this line if you only want the server available locally
          base: 'public',
          keepalive: true,
          middleware: function(connect, options) {
            return [
              require('connect-livereload')({
                port: config.watch.public.options.livereload
              }),
              connect.static(options.base)
            ];
          }
        }
      }
    },
    open: {
      server: {
        path: 'http://localhost:<%= connect.server.options.port %>'
      }
    },
    concurrent: {
      compile: {
        tasks: [
          'jade',
          'compile-sass',
          'concat',
          'copy'
        ],
        options: {
          logConcurrentOutput: false
        }
      },
      server: {
        tasks: [
          'connect',
          'open',
          'watch:jade',
          'watch:sass',
          'watch:copy',
          'watch:public'
        ],
        options: {
          logConcurrentOutput: true
        }
      }
    },
    useminPrepare: {
      html: 'public/index.html',
      options: {
        dest: 'public'
      }
    },
    usemin: {
      html: 'public/index.html'
    },
    'gh-pages': {
      public: {
        options: {
          base: 'public',
          message: 'Generated by generator-bespoke'
        },
        src: '**/*'
      }
    }
  };

  grunt.initConfig(config);

  // Load all Grunt tasks
  require('matchdep').filterDev('grunt-*').forEach(grunt.loadNpmTasks);

  grunt.registerTask('default', ['compile']);
  grunt.registerTask('compile-sass', ['sass', 'autoprefixer']);
  grunt.registerTask('compile', ['clean', 'concurrent:compile']);
  grunt.registerTask('server', ['compile', 'concurrent:server']);
  grunt.registerTask('deploy', ['default', 'gh-pages:public']);

};
